[package]
name = "karkinos_shared"
version = "0.2.0"
edition = "2021"

[lib]
name = "karkinos_shared"
crate-type = ["cdylib"]

[dependencies]
karkinos = { path = ".." }
ctor = { version = "0.4.2", optional = true }

[features]
onload = ["dep:ctor"]
user = []
